AWSTemplateFormatVersion: "2010-09-09"
Description:
  'This template will create the Transit Gateway.'

Resources:
  myTransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AmazonSideAsn: 65125
      Description: "TGW Test"
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "enable"
      DefaultRouteTablePropagation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
      - Key: Name
        Value: TestTGW

Outputs:
  tgwID:
    Description: Transit Gateway ID
    Value: !Ref myTransitGateway
    Export:
      Name: !Sub ${AWS::StackName}-tgwID    
  tgwArn:
    Description: Transit Gateway Arn
    Value: !Sub arn:aws-us-gov:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${myTransitGateway}
    Export:
      Name: !Sub ${AWS::StackName}-tgwArn